redirects:
  getting-started: getting-started.md
  getting-started/10-set-up-platform-agents: quick-start/set-up-agents.md
  getting-started/15-deploy-example-application: quick-start/deploy-example-application.md
  getting-started/30-run-experiment: quick-start/run-experiment.md
  install-configure: install-and-configure/install-agents/README.md
  install-configure/30-install-agents: install-and-configure/install-agents/README.md
  use: use-steadybit/experiments/README.md